spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/om
      username: root
      password: 1234
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
